package com.gabrieal.podcastapplication.models.podcast

data class PodcastModel (
    val alias: String?,
    val belt_name: String?,
    val category: List<String>?,
    val content: String?,
    val content_type: String?,
    val createdon: String?,
    val delisted: String?,
    val editedon: String?,
    val fbimage: String?,
    val guest_designations: List<String>?,
    val guest_names: List<String>?,
    val guest_organisations: List<String>?,
    val guests: List<String>?,
    val hidedownload: String?,
    val hidesponsor: String?,
    val id: String?,
    val image: String?,
    val interviewtime: String?,
    val mp3: String?,
    val mp3_duration: String?,
    val mp3file_size: String?,
    val pagetitle: String?,
    val parent: String?,
    val presenters: String?,
    val producers: String?,
    val publishedon: String?,
    val salutations: List<String>?,
    val selected_highlight: String?,
    val show_name: String?,
    val slug: String?,
    val tags: List<String>?
)